### ISSUE TITLE
 Inter wiki links to headings with brackets broken

### ISSUE THREAD

**Issue by viaLAN-joh** [humhub/wiki#125] opened 2020-04-29 12:44 UTC
In editor create headings with brackets in the name like this:
![humhub-modules-wiki-1](https://user-images.githubusercontent.com/7206463/80596987-7d5fa800-8a27-11ea-937c-dc92c8da151b.png)
* * * 
Create wiki links on another page results in this:
![humhub-modules-wiki-2](https://user-images.githubusercontent.com/7206463/80597036-936d6880-8a27-11ea-8299-56f33d42de35.png)

I think there is something wrong with the handling of brackets.

**Comment by Oremountainflorian** [comment] 2020-04-30 05:48
I also face some strange behaviour with links (mentionings)

### >Stream<
![grafik](https://user-images.githubusercontent.com/44228345/80676092-4e444780-8ab6-11ea-8bbf-02a96b560229.png)

### >Wiki<
![grafik](https://user-images.githubusercontent.com/44228345/80676180-80ee4000-8ab6-11ea-9055-d15fcd9f9273.png)

But I can't find out the reason, it doesn't seem to have to do with brackets or coma:

### >Stream<
![grafik](https://user-images.githubusercontent.com/44228345/80676255-abd89400-8ab6-11ea-8519-f7f77e885418.png)

**Comment by luke-** [comment] 2021-06-16 12:15
It is probably a simpler solution not to generate the () characters with such jump labels.

**Comment by yurabakhtin** [comment] 2021-06-18 12:04
@luke- Please see my tests, it must works on normal copy/paste url:

<img width="1889" alt="investigate_anchors" src="https://user-images.githubusercontent.com/6995524/122557978-2c08e280-d046-11eb-8227-a9be384b195f.png">

If we really need to exclude all unexpected chars to keep only letters, digits and some chars like `-`, `_`, we should modify the composer package `humhub-prosemirror`, I think the place is approximately here https://github.com/humhub/humhub-prosemirror/blob/master/src/editor/core/plugins/anchors/index.js#L38.

**Comment by luke-** [comment] 2021-06-18 16:31
@yurabakhtin  Ok, it has now worked for me too. There was a problem with my last test, but I can't reproduce this any more....

Then I would close the issue until further problems occur....

**Closed by luke-** 2021-06-18 16:31 UTC
Labels: bug, need investigation
