### ISSUE TITLE
HumHub v1.8.2 and Wiki v1.5.3 add new Site to Wiki fails

### ISSUE THREAD

**Issue by r4nc0r** [humhub/wiki#179] opened 2021-06-10 07:49 UTC
Hi, we are a business User of Humhub, and recently we updatet to Humhub v1.8.2 and also updated all Modules accordingly.
But now the Wiki Module (v1.5.3) throws an error on new Site creation

### What steps will reproduce the problem?
Go to a group and add the Wiki Module.
Go into the Wiki
Click on the green "+ new Site" Button

### What is the expected result?
The new Site add Dialog of the Wiki Module

### What do you get instead?
Internal Server error and the below error in the Admin Menu

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.8
| PHP version      |   7
| Operating system | debian+docker

~~~text
TypeError: Argument 1 passed to humhub\modules\content\widgets\richtext\ProsemirrorRichText::replaceLinkExtension() must be of the type string, null given, called in /var/www/localhost/htdocs/protected/modules/wiki/widgets/WikiRichText.php on line 69 and defined in /var/www/localhost/htdocs/protected/humhub/modules/content/widgets/richtext/ProsemirrorRichText.php:227
Stack trace: #0 /var/www/localhost/htdocs/protected/modules/wiki/widgets/WikiRichText.php(69): humhub\modules\content\widgets\richtext\ProsemirrorRichText::replaceLinkExtension() 
humhub/humhub#1 /var/www/localhost/htdocs/protected/modules/wiki/widgets/WikiRichText.php(25): humhub\modules\wiki\widgets\WikiRichText->parseWikiLinks() 
humhub/humhub#2 /var/www/localhost/htdocs/protected/humhub/modules/content/widgets/richtext/ProsemirrorRichText.php(156): humhub\modules\wiki\widgets\WikiRichText->parseOutput() 
humhub/humhub#3 /var/www/localhost/htdocs/protected/humhub/components/Widget.php(63): humhub\modules\content\widgets\richtext\ProsemirrorRichText->run() 
humhub/humhub#4 /var/www/localhost/htdocs/protected/humhub/modules/content/widgets/richtext/AbstractRichText.php(323): humhub\components\Widget::widget() 
humhub/humhub#5 [internal function]: humhub\modules\content\widgets\richtext\AbstractRichText::output() 
humhub/humhub#6 /var/www/localhost/htdocs/protected/humhub/modules/content/widgets/richtext/AbstractRichTextEditor.php(229): call_user_func() 
humhub/humhub#7 /var/www/localhost/htdocs/protected/humhub/modules/content/widgets/richtext/AbstractRichTextEditor.php(156): humhub\modules\content\widgets\richtext\AbstractRichTextEditor->editOutput() 
humhub/humhub#8 /var/www/localhost/htdocs/protected/humhub/components/Widget.php(63): humhub\modules\content\widgets\richtext\AbstractRichTextEditor->run() 
humhub/humhub#9 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/widgets/ActiveField.php(795): humhub\components\Widget::widget() 
humhub/humhub#10 /var/www/localhost/htdocs/protected/humhub/modules/ui/form/widgets/ActiveField.php(46): yii\widgets\ActiveField->widget() 
humhub/humhub#11 /var/www/localhost/htdocs/protected/modules/wiki/views/page/edit.php(45): humhub\modules\ui\form\widgets\ActiveField->widget() 
humhub/humhub#12 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/View.php(348): require('/var/www/localh...') 
humhub/humhub#13 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile() 
humhub/humhub#14 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile() 
humhub/humhub#15 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(410): yii\base\View->render() 
humhub/humhub#16 /var/www/localhost/htdocs/protected/modules/wiki/controllers/PageController.php(142): yii\base\Controller->render() 
humhub/humhub#17 [internal function]: humhub\modules\wiki\controllers\PageController->actionEdit() 
humhub/humhub#18 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array() 
humhub/humhub#19 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams() 
humhub/humhub#20 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Module.php(534): yii\base\Controller->runAction() 
humhub/humhub#21 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/web/Application.php(104): yii\base\Module->runAction() 
humhub/humhub#22 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(392): yii\web\Application->handleRequest() 
humhub/humhub#23 /var/www/localhost/htdocs/index.php(25): yii\base\Application->run() humhub/humhub#24 {main}
~~~

**Comment by luke-** [comment] 2021-06-10 08:35
@yurabakhtin Any idea?

**Comment by yurabakhtin** [comment] 2021-06-17 09:42
@luke- I could not reproduce the error. It seems the steps description has some wrong words and it should written like this:

- Go to a **Space** and **enable** the Wiki Module for the Space.
- Go into the Wiki (on left sidebar of the Space)
- Click on the green "+ New **page**" Button

If it is what means then I could not reproduce on the latest `master` branch version `1.8.3 (Unreleased)` + Wiki `1.6.0  (Unreleased)`. But I guess the code `replaceLinkExtension(string $text...)` requires the param `$text` to be only `string` so when there is `null` the error happens. The param type was added here https://github.com/humhub/humhub/commit/f2751e1#diff-2c77ab776525dd6b0323bb029437113f49defcfdc96c997821750a0120bf9e2dL283
So to avoid this I considered to remove the type requirement for the param, because I didn't find what code call the function with `null` instead of expecting string value.
PR https://github.com/humhub/humhub/pull/5130/files.

**Comment by luke-** [comment] 2021-06-21 20:31
@yurabakhtin I would prefer that we pass instead of `null` an empty string to the `replaceLinkExtension` method. What do you think?

**Comment by yurabakhtin** [comment] 2021-06-22 05:38
@luke- As I wrote I could not detect what code send `null`, probably some text field value in DB has `NULL` instead of empty string, and I think we cannot know what it is, and if we will detect this then we cannot be sure that in future another code/module will send `null` there, so this function should allow either `string` or `null`, please review my new changes for this in commit https://github.com/humhub/humhub/pull/5130/commits/4ee79c55e0ef30b5e079e64a26898a241a401c1a.

**Comment by luke-** [comment] 2021-06-22 08:43
@yurabakhtin Thanks! 

Will be fixed with the latest master.

**Closed by luke-** 2021-06-22 08:43 UTC
Labels: need investigation
